# Following resources will be made when setup.sh is executed. 
# If you rather want to use the resources you've already had for this material, please set the value the value bellow.

aws_region:   # The region your development environment is running will be set here. 
bucket_name:  # S3 bucket for running RoboMaker simulation. If you want to use specific S3 buckt, set that bucket name here. 
simulation_app_name: # Simulation application name. If you want to name specific name to the application, set the application name here.
robot_app_name:  # Robot application name. If you want to name specific name to the application, set the application name here.
iam_policy:   # IAM policy for running RoboMaker simulator. If you want to use specific IAM policy, set the IAM policy ARN here.
iam_role:     # IAM role for running RoboMaker simultor. If you want to use specific IAM role, set the IAM role ARN here.
robomaker_settings: # roboMakerSettings.json file will be automatically updated. If you don't want that functionality, set false here.
security_groups: # security group used in RoboMaker simulator. This will be security group for default VPC.  If you want to use specific security group, set the security groups here. ( with "- secutiry-group-name" format).
subnets: # subnets for RoboMaker simulator. This will be subnets for default VPC. If you want to use specific subnets, set the subnets here. (with "- subnets" format).
default_vpc: # This will have default VPC. You don't need to modify this part.
